// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {SP1EthereumLightClient} from "../src/SP1EthereumLightClient.sol";
import {ISP1Verifier} from "../src/interfaces/ISP1Verifier.sol";

/// @title MockSP1Verifier
/// @notice A mock verifier for testing with SP1_PROVER=mock fixtures.
contract MockSP1VerifierFixture is ISP1Verifier {
    function verifyProof(
        bytes32,
        bytes calldata,
        bytes calldata
    ) external pure override {
        // Always succeeds — used with mock proof fixtures
    }
}

/// @title SP1FixtureTest
/// @notice Tests the on-chain light client contract using proof fixtures
///         generated by `cargo run --release --bin evm`.
///
///         These tests simulate the FULL on-chain flow:
///         1. Deploy the contract with the correct vkey from the fixture
///         2. Initialize the light client at a prior slot
///         3. Submit the proof + publicValues from the fixture to advance the head
///         4. Verify all state was updated correctly
///
///         With SP1_PROVER=mock, the proof bytes are empty (0x) so a MockVerifier is used.
///         With SP1_PROVER=local or network, you'd use the real SP1Verifier contract.
contract SP1FixtureTest is Test {
    using stdJson for string;

    SP1EthereumLightClient public lightClient;
    MockSP1VerifierFixture public mockVerifier;

    uint32 constant MIN_PARTICIPATION = 342; // 2/3 of 512

    // Fixture data
    struct ProofFixture {
        uint64 finalizedSlot;
        bytes32 finalizedHeaderRoot;
        bytes32 finalizedStateRoot;
        bytes32 currentSyncCommitteeHash;
        bytes32 nextSyncCommitteeHash;
        uint32 participation;
        bytes32 vkey;
        bytes publicValues;
        bytes proof;
    }

    /// @notice Load a proof fixture from JSON file.
    function loadFixture(string memory filename) internal view returns (ProofFixture memory) {
        string memory root = vm.projectRoot();
        string memory path = string.concat(root, "/src/fixtures/", filename);
        string memory json = vm.readFile(path);

        ProofFixture memory fixture;
        fixture.finalizedSlot = uint64(json.readUint(".finalizedSlot"));
        fixture.finalizedHeaderRoot = json.readBytes32(".finalizedHeaderRoot");
        fixture.finalizedStateRoot = json.readBytes32(".finalizedStateRoot");
        fixture.currentSyncCommitteeHash = json.readBytes32(".currentSyncCommitteeHash");
        fixture.nextSyncCommitteeHash = json.readBytes32(".nextSyncCommitteeHash");
        fixture.participation = uint32(json.readUint(".participation"));
        fixture.vkey = json.readBytes32(".vkey");
        fixture.publicValues = json.readBytes(".publicValues");
        fixture.proof = json.readBytes(".proof");

        return fixture;
    }

    // =========================================================================
    // Groth16 Fixture Tests
    // =========================================================================

    function test_groth16_fixture_loads() public view {
        ProofFixture memory f = loadFixture("groth16-fixture.json");

        console.log("=== Groth16 Fixture ===");
        console.log("Finalized Slot:", f.finalizedSlot);
        console.log("Participation: ", f.participation);
        console.log("VKey:");
        console.logBytes32(f.vkey);
        console.log("Header Root:");
        console.logBytes32(f.finalizedHeaderRoot);
        console.log("State Root:");
        console.logBytes32(f.finalizedStateRoot);
        console.log("SC Hash:");
        console.logBytes32(f.currentSyncCommitteeHash);
        console.log("Public Values length:", f.publicValues.length);
        console.log("Proof length:        ", f.proof.length);

        assertEq(f.finalizedSlot, 6000000);
        assertEq(f.participation, 512);
        assertTrue(f.publicValues.length > 0);
        assertEq(f.vkey, 0x00c0d2560cdf46cef2bf7972d4fbcb57c292dcd2e6e014fad14afbe3d6820fb2);
    }

    function test_groth16_fixture_full_flow() public {
        ProofFixture memory f = loadFixture("groth16-fixture.json");

        // Deploy with the vkey from the fixture
        mockVerifier = new MockSP1VerifierFixture();
        lightClient = new SP1EthereumLightClient(
            address(mockVerifier),
            f.vkey,
            MIN_PARTICIPATION
        );

        // Initialize at a slot BEFORE the fixture's finalized slot
        // Using the same sync committee hash so the update will be accepted
        uint64 initSlot = f.finalizedSlot - 8192; // ~1 day before
        lightClient.initialize(
            initSlot,
            bytes32(uint256(0x1111)),               // placeholder header root
            bytes32(uint256(0x2222)),               // placeholder state root
            f.currentSyncCommitteeHash              // must match fixture's SC hash
        );

        assertEq(lightClient.head(), initSlot);
        assertTrue(lightClient.initialized());

        console.log("");
        console.log("=== Groth16 Full Flow ===");
        console.log("Initialized at slot:", initSlot);

        // Submit the proof from the fixture to advance the head
        lightClient.update(f.publicValues, f.proof);

        // Verify ALL state was updated
        assertEq(lightClient.head(), f.finalizedSlot);
        assertEq(lightClient.finalizedHeaderRoot(), f.finalizedHeaderRoot);
        assertEq(lightClient.finalizedStateRoot(), f.finalizedStateRoot);
        assertEq(lightClient.currentSyncCommitteeHash(), f.currentSyncCommitteeHash);
        assertTrue(lightClient.isSlotFinalized(f.finalizedSlot));

        // Verify historical lookups work
        assertEq(lightClient.getFinalizedHeaderRoot(f.finalizedSlot), f.finalizedHeaderRoot);
        assertEq(lightClient.getFinalizedStateRoot(f.finalizedSlot), f.finalizedStateRoot);

        console.log("Head advanced to:   ", lightClient.head());
        console.log("Header root stored:  true");
        console.log("State root stored:   true");
        console.log("Slot finalized:      true");
        console.log("GROTH16 FLOW: PASSED");
    }

    // =========================================================================
    // PLONK Fixture Tests
    // =========================================================================

    function test_plonk_fixture_loads() public view {
        ProofFixture memory f = loadFixture("plonk-fixture.json");

        console.log("=== PLONK Fixture ===");
        console.log("Finalized Slot:", f.finalizedSlot);
        console.log("Participation: ", f.participation);
        console.log("VKey:");
        console.logBytes32(f.vkey);

        assertEq(f.finalizedSlot, 6000000);
        assertEq(f.participation, 512);
        assertEq(f.vkey, 0x00c0d2560cdf46cef2bf7972d4fbcb57c292dcd2e6e014fad14afbe3d6820fb2);
    }

    function test_plonk_fixture_full_flow() public {
        ProofFixture memory f = loadFixture("plonk-fixture.json");

        mockVerifier = new MockSP1VerifierFixture();
        lightClient = new SP1EthereumLightClient(
            address(mockVerifier),
            f.vkey,
            MIN_PARTICIPATION
        );

        uint64 initSlot = f.finalizedSlot - 8192;
        lightClient.initialize(
            initSlot,
            bytes32(uint256(0x1111)),
            bytes32(uint256(0x2222)),
            f.currentSyncCommitteeHash
        );

        console.log("");
        console.log("=== PLONK Full Flow ===");
        console.log("Initialized at slot:", initSlot);

        lightClient.update(f.publicValues, f.proof);

        assertEq(lightClient.head(), f.finalizedSlot);
        assertEq(lightClient.finalizedHeaderRoot(), f.finalizedHeaderRoot);
        assertEq(lightClient.finalizedStateRoot(), f.finalizedStateRoot);
        assertTrue(lightClient.isSlotFinalized(f.finalizedSlot));

        console.log("Head advanced to:   ", lightClient.head());
        console.log("PLONK FLOW: PASSED");
    }

    // =========================================================================
    // Decode Public Values Test
    // =========================================================================

    function test_groth16_decode_public_values() public view {
        ProofFixture memory f = loadFixture("groth16-fixture.json");

        // Decode the raw publicValues bytes the same way the contract does
        SP1EthereumLightClient.LightClientPublicValues memory pv = abi.decode(
            f.publicValues,
            (SP1EthereumLightClient.LightClientPublicValues)
        );

        console.log("");
        console.log("=== Decoded Public Values (Groth16) ===");
        console.log("finalizedSlot:       ", pv.finalizedSlot);
        console.log("participation:       ", pv.participation);
        console.log("numStorageSlots:     ", pv.numStorageSlots);
        console.log("numL2StorageSlots:   ", pv.numL2StorageSlots);
        console.log("storageProofAddress: ", pv.storageProofAddress);

        // Verify decoded values match fixture metadata
        assertEq(pv.finalizedSlot, f.finalizedSlot);
        assertEq(pv.finalizedHeaderRoot, f.finalizedHeaderRoot);
        assertEq(pv.finalizedStateRoot, f.finalizedStateRoot);
        assertEq(pv.currentSyncCommitteeHash, f.currentSyncCommitteeHash);
        assertEq(pv.nextSyncCommitteeHash, f.nextSyncCommitteeHash);
        assertEq(pv.participation, f.participation);

        // These are 0 since mock data doesn't include storage/L2 proofs
        assertEq(pv.numStorageSlots, 0);
        assertEq(pv.numL2StorageSlots, 0);
        assertEq(pv.storageProofAddress, address(0));
    }

    // =========================================================================
    // Multi-Update Simulation (consecutive proof submissions)
    // =========================================================================

    function test_simulate_multi_update_flow() public {
        ProofFixture memory f = loadFixture("groth16-fixture.json");

        mockVerifier = new MockSP1VerifierFixture();
        lightClient = new SP1EthereumLightClient(
            address(mockVerifier),
            f.vkey,
            MIN_PARTICIPATION
        );

        // Initialize way before the fixture slot
        uint64 initSlot = 5000000;
        lightClient.initialize(
            initSlot,
            bytes32(uint256(0xaaaa)),
            bytes32(uint256(0xbbbb)),
            f.currentSyncCommitteeHash
        );

        console.log("");
        console.log("=== Multi-Update Simulation ===");
        console.log("Init slot:", initSlot);

        // First update: from fixture
        lightClient.update(f.publicValues, f.proof);
        assertEq(lightClient.head(), 6000000);
        console.log("Update 1 -> slot:", lightClient.head());

        // Second update: simulate a future slot with same SC
        SP1EthereumLightClient.LightClientPublicValues memory pv2;
        pv2.finalizedSlot = 6008192;  // ~1 epoch later
        pv2.finalizedHeaderRoot = bytes32(uint256(0xdead));
        pv2.finalizedStateRoot = bytes32(uint256(0xbeef));
        pv2.currentSyncCommitteeHash = f.currentSyncCommitteeHash;
        pv2.participation = 480;

        lightClient.update(abi.encode(pv2), hex"");
        assertEq(lightClient.head(), 6008192);
        console.log("Update 2 -> slot:", lightClient.head());

        // Third update: with sync committee rotation
        SP1EthereumLightClient.LightClientPublicValues memory pv3;
        pv3.finalizedSlot = 6016384;
        pv3.finalizedHeaderRoot = bytes32(uint256(0xcafe));
        pv3.finalizedStateRoot = bytes32(uint256(0xfeed));
        pv3.currentSyncCommitteeHash = f.currentSyncCommitteeHash;
        pv3.nextSyncCommitteeHash = bytes32(uint256(0x9999));
        pv3.participation = 450;

        lightClient.update(abi.encode(pv3), hex"");
        assertEq(lightClient.head(), 6016384);
        assertEq(lightClient.nextSyncCommitteeHash(), bytes32(uint256(0x9999)));
        console.log("Update 3 -> slot:", lightClient.head());
        console.log("Next SC rotated:  true");

        // Verify all 4 slots are finalized and queryable
        assertTrue(lightClient.isSlotFinalized(initSlot));
        assertTrue(lightClient.isSlotFinalized(6000000));
        assertTrue(lightClient.isSlotFinalized(6008192));
        assertTrue(lightClient.isSlotFinalized(6016384));
        console.log("All 4 slots finalized: true");
        console.log("MULTI-UPDATE: PASSED");
    }

    // =========================================================================
    // Gas Estimation
    // =========================================================================

    function test_gas_estimation_update() public {
        ProofFixture memory f = loadFixture("groth16-fixture.json");

        mockVerifier = new MockSP1VerifierFixture();
        lightClient = new SP1EthereumLightClient(
            address(mockVerifier),
            f.vkey,
            MIN_PARTICIPATION
        );

        lightClient.initialize(
            f.finalizedSlot - 8192,
            bytes32(uint256(0x1111)),
            bytes32(uint256(0x2222)),
            f.currentSyncCommitteeHash
        );

        uint256 gasBefore = gasleft();
        lightClient.update(f.publicValues, f.proof);
        uint256 gasUsed = gasBefore - gasleft();

        console.log("");
        console.log("=== Gas Estimation ===");
        console.log("Gas used for update():", gasUsed);
        console.log("(Note: real Groth16/PLONK verification costs ~300k+ gas)");
        console.log("(Mock verifier is near zero for the verifyProof call)");
    }
}
