// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {ISP1Verifier} from "./interfaces/ISP1Verifier.sol";

/// @title SP1EthereumLightClient
/// @notice On-chain Ethereum light client backed by SP1 zero-knowledge proofs.
///
/// @dev This contract stores verified beacon chain state and accepts SP1 proofs
///      to advance the light client. Each proof verifies:
///      - Sync committee participation (supermajority threshold)
///      - Finality Merkle proof (finalized header in beacon state)
///      - Domain & signing root computation
///      - (Phase 3+) BLS aggregate signature verification
///
///      The contract maintains:
///      - Latest finalized header root & state root per slot
///      - Current and next sync committee hashes
///      - Historical finalized roots for lookups
///
/// @author Generated by SP1 Ethereum Light Client project
contract SP1EthereumLightClient {
    // =========================================================================
    // Types
    // =========================================================================

    /// @notice Decoded public values from an SP1 light client proof.
    struct LightClientPublicValues {
        uint64 finalizedSlot;
        bytes32 finalizedHeaderRoot;
        bytes32 finalizedStateRoot;
        bytes32 currentSyncCommitteeHash;
        bytes32 nextSyncCommitteeHash;
        uint32 participation;
        uint32 numStorageSlots;
        address storageProofAddress;
        bytes32 storageProofStorageRoot;
        uint32 numL2StorageSlots;
        bytes32 l2StateRoot;
    }

    // =========================================================================
    // State
    // =========================================================================

    /// @notice The SP1 verifier contract (Groth16 or PLONK).
    ISP1Verifier public immutable verifier;

    /// @notice The verification key hash for the light client SP1 program.
    bytes32 public immutable programVKey;

    /// @notice Minimum sync committee participation required (e.g., 342 = 2/3 of 512).
    uint32 public immutable minParticipation;

    /// @notice The latest verified finalized slot.
    uint64 public head;

    /// @notice The finalized beacon block header root for the latest slot.
    bytes32 public finalizedHeaderRoot;

    /// @notice The finalized beacon state root for the latest slot.
    bytes32 public finalizedStateRoot;

    /// @notice Hash of the current sync committee.
    bytes32 public currentSyncCommitteeHash;

    /// @notice Hash of the next sync committee (zero if not yet rotated).
    bytes32 public nextSyncCommitteeHash;

    /// @notice Mapping from slot number to finalized header root.
    /// @dev Allows historical lookups for cross-chain verification.
    mapping(uint64 => bytes32) public finalizedHeaderRoots;

    /// @notice Mapping from slot number to finalized state root.
    mapping(uint64 => bytes32) public finalizedStateRoots;

    /// @notice Whether the contract has been initialized with a trusted checkpoint.
    bool public initialized;

    /// @notice Latest verified L1 storage proof results (slot → address → storageRoot).
    mapping(uint64 => mapping(address => bytes32)) public verifiedStorageRoots;

    /// @notice Latest verified L2 state roots per finalized slot.
    mapping(uint64 => bytes32) public verifiedL2StateRoots;

    // =========================================================================
    // Events
    // =========================================================================

    /// @notice Emitted when the light client head is advanced.
    event HeadUpdate(
        uint64 indexed slot,
        bytes32 finalizedHeaderRoot,
        bytes32 finalizedStateRoot,
        uint32 participation
    );

    /// @notice Emitted when the sync committee rotates.
    event SyncCommitteeRotation(
        uint64 indexed slot,
        bytes32 oldCommitteeHash,
        bytes32 newCommitteeHash
    );

    /// @notice Emitted when the light client is initialized.
    event Initialized(
        uint64 slot,
        bytes32 finalizedHeaderRoot,
        bytes32 syncCommitteeHash
    );

    /// @notice Emitted when a storage proof is verified for an L1 account.
    event StorageProofVerified(
        uint64 indexed slot,
        address indexed account,
        bytes32 storageRoot,
        uint32 numSlots
    );

    /// @notice Emitted when an L2 state root is verified.
    event L2StateRootVerified(
        uint64 indexed slot,
        bytes32 l2StateRoot,
        uint32 numSlots
    );

    // =========================================================================
    // Errors
    // =========================================================================

    error AlreadyInitialized();
    error NotInitialized();
    error SlotNotNewer(uint64 currentHead, uint64 newSlot);
    error InsufficientParticipation(uint32 got, uint32 min);
    error SyncCommitteeMismatch(bytes32 expected, bytes32 got);
    error InvalidProof();

    // =========================================================================
    // Constructor
    // =========================================================================

    /// @param _verifier Address of the SP1 verifier contract.
    /// @param _programVKey Verification key hash of the light client program.
    /// @param _minParticipation Minimum sync committee participation (e.g., 342).
    constructor(
        address _verifier,
        bytes32 _programVKey,
        uint32 _minParticipation
    ) {
        verifier = ISP1Verifier(_verifier);
        programVKey = _programVKey;
        minParticipation = _minParticipation;
    }

    // =========================================================================
    // Initialization
    // =========================================================================

    /// @notice Initialize the light client with a trusted checkpoint.
    /// @dev This should be called once with a known-good finalized state.
    ///      In production, this would be set by a trusted party or governance.
    /// @param _slot The trusted finalized slot.
    /// @param _finalizedHeaderRoot The header root at the trusted slot.
    /// @param _finalizedStateRoot The state root at the trusted slot.
    /// @param _syncCommitteeHash Hash of the current sync committee at the trusted slot.
    function initialize(
        uint64 _slot,
        bytes32 _finalizedHeaderRoot,
        bytes32 _finalizedStateRoot,
        bytes32 _syncCommitteeHash
    ) external {
        if (initialized) revert AlreadyInitialized();

        head = _slot;
        finalizedHeaderRoot = _finalizedHeaderRoot;
        finalizedStateRoot = _finalizedStateRoot;
        currentSyncCommitteeHash = _syncCommitteeHash;
        initialized = true;

        finalizedHeaderRoots[_slot] = _finalizedHeaderRoot;
        finalizedStateRoots[_slot] = _finalizedStateRoot;

        emit Initialized(_slot, _finalizedHeaderRoot, _syncCommitteeHash);
    }

    // =========================================================================
    // Core: Update with SP1 Proof
    // =========================================================================

    /// @notice Advance the light client head by submitting an SP1 proof.
    /// @dev The proof must verify a light client update from the current state.
    ///      The public values in the proof are ABI-decoded and validated.
    /// @param publicValues ABI-encoded LightClientPublicValues.
    /// @param proofBytes The SP1 proof bytes (Groth16 or PLONK).
    function update(
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external {
        if (!initialized) revert NotInitialized();

        // Step 1: Verify the SP1 proof on-chain
        verifier.verifyProof(programVKey, publicValues, proofBytes);

        // Step 2: Decode the public values
        LightClientPublicValues memory pv = abi.decode(
            publicValues,
            (LightClientPublicValues)
        );

        // Step 3: Validate the update
        _validateUpdate(pv);

        // Step 4: Apply the update
        _applyUpdate(pv);
    }

    // =========================================================================
    // Internal Validation
    // =========================================================================

    /// @dev Validate that the light client update is acceptable.
    function _validateUpdate(LightClientPublicValues memory pv) internal view {
        // The new slot must be strictly newer than the current head
        if (pv.finalizedSlot <= head) {
            revert SlotNotNewer(head, pv.finalizedSlot);
        }

        // Must meet minimum participation threshold
        if (pv.participation < minParticipation) {
            revert InsufficientParticipation(pv.participation, minParticipation);
        }

        // The proof's current sync committee must match our stored state
        if (pv.currentSyncCommitteeHash != currentSyncCommitteeHash) {
            // Allow matching against next committee (period boundary crossing)
            if (
                nextSyncCommitteeHash != bytes32(0) &&
                pv.currentSyncCommitteeHash == nextSyncCommitteeHash
            ) {
                // Valid: committee rotated at period boundary
            } else {
                revert SyncCommitteeMismatch(
                    currentSyncCommitteeHash,
                    pv.currentSyncCommitteeHash
                );
            }
        }
    }

    /// @dev Apply a validated update to storage.
    function _applyUpdate(LightClientPublicValues memory pv) internal {
        // Check for sync committee rotation
        bool isRotation = pv.nextSyncCommitteeHash != bytes32(0);

        // If the proof's current committee matches our next committee,
        // this means we've crossed a period boundary
        if (pv.currentSyncCommitteeHash == nextSyncCommitteeHash && nextSyncCommitteeHash != bytes32(0)) {
            bytes32 oldHash = currentSyncCommitteeHash;
            currentSyncCommitteeHash = nextSyncCommitteeHash;
            nextSyncCommitteeHash = bytes32(0);

            emit SyncCommitteeRotation(pv.finalizedSlot, oldHash, currentSyncCommitteeHash);
        }

        // Store the new next sync committee if provided
        if (isRotation) {
            bytes32 oldNext = nextSyncCommitteeHash;
            nextSyncCommitteeHash = pv.nextSyncCommitteeHash;

            if (oldNext == bytes32(0)) {
                emit SyncCommitteeRotation(
                    pv.finalizedSlot,
                    currentSyncCommitteeHash,
                    pv.nextSyncCommitteeHash
                );
            }
        }

        // Update head
        head = pv.finalizedSlot;
        finalizedHeaderRoot = pv.finalizedHeaderRoot;
        finalizedStateRoot = pv.finalizedStateRoot;

        // Store in history
        finalizedHeaderRoots[pv.finalizedSlot] = pv.finalizedHeaderRoot;
        finalizedStateRoots[pv.finalizedSlot] = pv.finalizedStateRoot;

        emit HeadUpdate(
            pv.finalizedSlot,
            pv.finalizedHeaderRoot,
            pv.finalizedStateRoot,
            pv.participation
        );

        // Store L1 storage proof results if present
        if (pv.numStorageSlots > 0) {
            verifiedStorageRoots[pv.finalizedSlot][pv.storageProofAddress] = pv.storageProofStorageRoot;
            emit StorageProofVerified(
                pv.finalizedSlot,
                pv.storageProofAddress,
                pv.storageProofStorageRoot,
                pv.numStorageSlots
            );
        }

        // Store L2 state root if present
        if (pv.numL2StorageSlots > 0) {
            verifiedL2StateRoots[pv.finalizedSlot] = pv.l2StateRoot;
            emit L2StateRootVerified(
                pv.finalizedSlot,
                pv.l2StateRoot,
                pv.numL2StorageSlots
            );
        }
    }

    // =========================================================================
    // View Functions
    // =========================================================================

    /// @notice Get the finalized header root for a specific slot.
    /// @param slot The slot to query.
    /// @return The header root, or bytes32(0) if not stored.
    function getFinalizedHeaderRoot(uint64 slot) external view returns (bytes32) {
        return finalizedHeaderRoots[slot];
    }

    /// @notice Get the finalized state root for a specific slot.
    /// @param slot The slot to query.
    /// @return The state root, or bytes32(0) if not stored.
    function getFinalizedStateRoot(uint64 slot) external view returns (bytes32) {
        return finalizedStateRoots[slot];
    }

    /// @notice Check if a specific slot has been finalized.
    /// @param slot The slot to check.
    /// @return True if the slot has been verified and stored.
    function isSlotFinalized(uint64 slot) external view returns (bool) {
        return finalizedHeaderRoots[slot] != bytes32(0);
    }

    /// @notice Get the current light client state summary.
    /// @return _head The latest finalized slot.
    /// @return _headerRoot The latest finalized header root.
    /// @return _stateRoot The latest finalized state root.
    /// @return _currentSC Hash of the current sync committee.
    /// @return _nextSC Hash of the next sync committee.
    function getState()
        external
        view
        returns (
            uint64 _head,
            bytes32 _headerRoot,
            bytes32 _stateRoot,
            bytes32 _currentSC,
            bytes32 _nextSC
        )
    {
        return (
            head,
            finalizedHeaderRoot,
            finalizedStateRoot,
            currentSyncCommitteeHash,
            nextSyncCommitteeHash
        );
    }

    /// @notice Get the verified storage root for an account at a finalized slot.
    /// @param slot The finalized slot.
    /// @param account The L1 contract address.
    /// @return The storage root, or bytes32(0) if not proven.
    function getVerifiedStorageRoot(uint64 slot, address account) external view returns (bytes32) {
        return verifiedStorageRoots[slot][account];
    }

    /// @notice Get the verified L2 state root at a finalized slot.
    /// @param slot The finalized slot.
    /// @return The L2 state root, or bytes32(0) if not proven.
    function getVerifiedL2StateRoot(uint64 slot) external view returns (bytes32) {
        return verifiedL2StateRoots[slot];
    }
}
